### ISSUE TITLE
Consider enabling *warn-on-reflection*

### ISSUE THREAD

**Issue by chen-factual** [Factual/geo#18]
Clojure reflection eats up a surprising amount of execution time. I see a lot of type-hinting in the codebase here, which tells me we care about compute times.

A simple example:
```clojure
(facts "benchmark linestring"
       (time
        (dotimes [_ 100000]
          (linestring [(coordinate 30 70) (coordinate 31 71)] 4326))))
```

Master: `"Elapsed time: 272.940221 msecs"`
With exhaustive type hinting: `"Elapsed time: 34.371557 msecs"`

I have sample code on `feature/type-hints`.

**Comment by worace** [comment]
done thanks to https://github.com/Factual/geo/pull/24
