### ISSUE TITLE
2.0 Release

### ISSUE THREAD

**Issue by worace** [Factual/geo#29]
Heads up @chen-factual and @willcohen I think we're about ready for a final 2.0 release.

I have started a branch at https://github.com/Factual/geo/tree/release/2.0.0 which is what I'm hoping to release for that version. So any bugfixes or last minute things will need to get onto that branch. We have been using the `2.0.0-rc-3` version for a bit internally and so far it seems mostly good.

I'm hoping to merge @willcohen's H3 branch soon as well but am thinking we'll target that for a subsequent `2.1` release

**Comment by willcohen** [comment]
If the H3 branch is going to wait for 2.1, it might still be good to have 2.0 be rebased off master. The changes in master from #27 do fix a bug in rc3 (the workaround until then is for the user to project points to WGS84 before calling latitude and longitude). #24 is less important, I suppose, but doesn't seem like it'd hurt anything.

**Comment by worace** [comment]
@willcohen my bad i rebased it this morning but had forgotten to update my local master. Should be updated. I definitely want to keep porting any bugfixes and such onto the 2.0.0 branch, just leaving off major features like H3.

**Comment by willcohen** [comment]
Okay! Let me know what, if anything, would be helpful for 2.0.

**Comment by chen-factual** [comment]
Can you pull in https://github.com/Factual/geo/pull/28 for 2.0?

**Comment by worace** [comment]
@chen-factual yes

**Comment by worace** [comment]
@willcohen @chen-factual We've been running several things on the latest 2.0 RC for a week or 2 now and it seems to be solid. I'm still a little nervous we're going to uncover more of these "forgot to set Default SRID" for some code path or other, but I guess we can just deal with them as they come up.

I am probably going to cut the final 2.0 release this week, unless anyone has objections.

**Comment by willcohen** [comment]
I think dropping 1.6 is quite reasonable.

**Comment by worace** [comment]
OK this is done. Long live `[factual/geo "2.0.0"]`: https://clojars.org/factual/geo

I also pushed updated docs to http://factual.github.io/geo/2.0.0/index.html

Big kudos to @willcohen; most of the work in this release was yours. Hope to push out a 2.1.0 with all the H3 stuff shortly.

**Comment by willcohen** [comment]
This is very exciting! We should eventually get an rc1 of 2.1 that’s based on the latest master with the changed polyfill stuff (though hopefully that becomes more unnecessary [with h3 4.0](https://github.com/uber/h3/pull/100) and we can change it internally/transparently anytime after 2.1.).

Now that all the projection stuff is official we’ll keep working on removing all of our internal cast-to-and-from-wgs84 workarounds where our JTS objects have been interacting with ‘geo’ to date and hopefully this helps uncover any remaining default SRID sorts of issues.

I’m traveling the latter half of August so let me know if there’s anything I can help wrap up before then.

Thanks for all the help!
