### ISSUE TITLE
`read-wkt` not thread-safe

### ISSUE THREAD

**Issue by martinzding** [Factual/geo#47]
The `read-wkt` function at https://github.com/Factual/geo/blob/master/src/geo/io.clj#L28 is using a global `wkt-reader` instance, which causes the WKT strings to be truncated when multiple threads call this function at the same time.

The solution is to make `read-wkt` thread-safe. I'm considering using Java's ThreadLocal, but I'm totally open to other ideas as well.

**Comment by willcohen** [comment]
Are you calling this from Clojure or another JVM language? I see that geotrellis uses a `ThreadLocal` [here](https://github.com/locationtech/geotrellis/blob/master/vector/src/main/scala/geotrellis/vector/io/WKT/WKT.scala) for a similar reason. It seems like the simplest solution would just be to make the srid-less invocation of `read-wkt` always call a new `WKTReader` instead of using the global one, just like the `(read-wkt wkt srid)` does already, unless you think the performance overhead of making new readers each time is big enough that we should start managing them per-thread.

**Comment by martinzding** [comment]
Actually `jts-1.16.0` made the tokenizer a stack variable instead of a class member, which made it thread-safe already:
https://github.com/locationtech/jts/commit/b464d54960cf0c99195a0f93a26ccfeab55c7f55#diff-fcfd509a6c768219464b2913da1145ee

So bumping the geo version to `2.1.1` and jts version to `1.16.0` solved the problem for me!

Thanks @willcohen . I'm closing this ticket.

**Comment by worace** [comment]
wow, nice find and even better to get a free fix for it. I wonder if we have any similar concerns around our GeoJSON or WKB deserialization?

I suspect the approaches @willcohen outlined above are probably the way to go -- either just initialize a new reader each time (which may be fine assuming they don't have a lot of initialization cost), or do the thread local thing.

**Comment by martinzding** [comment]
I'd vote for the "initialize a new object each time" approach. It look like the class constructors are fairly cheap, and also this would make the code easier to read and maintain.

**Comment by willcohen** [comment]
That seems right. I'll think about if there's something more efficient, but it looks like Clojure's overhead already outweighs the cost of the constructor, so we could just use something like `(.read (WKTReader. gf-wgs84) wkt)` to make a new reader and still at least get to keep the global WGS84 `GeometryFactory`. [WKTReader](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/io/WKBReader.java) still says it's not thread-safe, so it's probably good to make a change either way.

Reading a WKT using a new EPSG:4326 WKTReader each time: 2 nanoseconds
```clojure
(let [test-wkt (slurp "test/resources/wkt")
      fn-with-new-reader (fn [^String wkt]
                           (.read (WKTReader. gf-wgs84) wkt))]
  (quick-bench (fn-with-new-reader test-wkt)))
Evaluation count : 284856 in 6 samples of 47476 calls.
             Execution time mean : 1.982421 µs
    Execution time std-deviation : 29.864933 ns
   Execution time lower quantile : 1.957447 µs ( 2.5%)
   Execution time upper quantile : 2.030929 µs (97.5%)
                   Overhead used : 2.031810 ns

Found 1 outliers in 6 samples (16.6667 %)
	low-severe	 1 (16.6667 %)
 Variance from outliers : 13.8889 % Variance is moderately inflated by outliers
```
Doing the same thing but with a new GeometryFactory each time: 2 nanoseconds
```clojure
(let [test-wkt (slurp "test/resources/wkt")
      fn-with-new-reader (fn [^String wkt]
                           (.read (WKTReader. (jts/gf 4326)) wkt))]
  (quick-bench (fn-with-new-reader test-wkt)))
Evaluation count : 301194 in 6 samples of 50199 calls.
             Execution time mean : 2.020891 µs
    Execution time std-deviation : 28.517955 ns
   Execution time lower quantile : 1.994572 µs ( 2.5%)
   Execution time upper quantile : 2.054550 µs (97.5%)
                   Overhead used : 2.031810 ns
```

Using the existing global var and the existing multi-arity function: just over 2 nanoseconds
```clojure
(let [test-wkt (slurp "test/resources/wkt")]
  (quick-bench (read-wkt test-wkt)))
Evaluation count : 260712 in 6 samples of 43452 calls.
             Execution time mean : 2.060676 µs
    Execution time std-deviation : 49.032248 ns
   Execution time lower quantile : 2.015295 µs ( 2.5%)
   Execution time upper quantile : 2.106556 µs (97.5%)
                   Overhead used : 2.031810 ns
```

Using the existing read-wkt function and global wkt-reader but bypassing the arity check, 1.9 nanoseconds:
```clojure
(let [test-wkt (slurp "test/resources/wkt")]
  (quick-bench (.read wkt-reader ^String test-wkt)))
Evaluation count : 278904 in 6 samples of 46484 calls.
             Execution time mean : 1.899847 µs
    Execution time std-deviation : 7.707583 ns
   Execution time lower quantile : 1.892717 µs ( 2.5%)
   Execution time upper quantile : 1.909076 µs (97.5%)
                   Overhead used : 2.031810 ns
