### ISSUE TITLE
to-geojson and parse-geojson don't compose

### ISSUE THREAD

**Issue by crclark** [Factual/geo#60]
It would be nice if we could easily convert between formats using `geo.io`. I'm trying to convert GeoJSON to WKT.

`(geo-io/to-wkt (geo-io/parse-geojson geojson-point))`

throws

`No implementation of method: :to-jts of protocol: #'geo.spatial/Shapelike found for class: org.wololo.geojson.Point`

The same is thrown even if I try to round-trip from and to geojson:

`(geo-io/to-geojson (geo-io/parse-geojson geojson-point))`

**Comment by worace** [comment]
Hey @crclark thanks for raising this point. I think we are mostly using that `parse-geojson` function internally for wrapping the java geojson library we are using to do the actual parsing, so I'm not sure it will have the best utility for combining with other functions as you are showing.

The most useful functions in geo.io are probably the various `read-*` ones, and in the case of `read-geojson` it handles the broadest possible case by coercing everything to a collection of feature-like maps:

```clj
(-> "{\"type\": \"Point\", \"coordinates\":[1.0, 2.0]}" read-geojson)
({:properties {}, :geometry #object[org.locationtech.jts.geom.Point 0x46c2ef5d "POINT (1 2)"]})
```

So you could potentially use that in combination with some additional processing:

```clj
(->> "{\"type\": \"Point\", \"coordinates\":[1.0, 2.0]}" read-geojson (map :geometry) (map to-wkt))
("POINT (1 2)")
```

The nice thing about this approach is that it will work for every geojson type, whether a Feature, FeatureCollection, or Geometry.


Or, if you only need to work on a single geometry, there is also a `read-geometry` function we use internally to convert those `org.wololo.geojson` types into JTS types, which could also be used:

```clj
(->> "{\"type\": \"Point\", \"coordinates\":[1.0, 2.0]}" parse-geojson read-geometry to-wkt)
"POINT (1 2)"
```

Does that work well enough for your use case? Apologies if it is confusing; we could probably do better about documenting how to use all of these various functions.

**Comment by worace** [comment]
Going to close this as inactive, hopefully that last response was sufficient.
